Repository neuralmagic/sparsezoo, pull requests merged in 2023-06, with the labels that each got.

#323 [Cherry pick] Sparsezoo stdout fix (#322)
  src/sparsezoo/analytics.py
  src/sparsezoo/utils/gdpr.py
  src/sparsezoo/utils/suppress.py
Labels: bug, 1.5 release

#324 [analytics] Made suppression fixes
  src/sparsezoo/analytics.py
  src/sparsezoo/utils/gdpr.py
  src/sparsezoo/utils/helpers.py
Labels: 1.5 release

#331 Deprecate Py37
  .github/ISSUE_TEMPLATE/bug_report.md
  DEVELOPING.md
  README.md
  setup.py
Labels: mle-team

#332 Update numpy 1.21.6
  setup.py
Labels: enhancement

#338 [Bug-fix] Set explicit ORT providers
  src/sparsezoo/inference/inference_runner.py
  src/sparsezoo/utils/node_inference.py
Labels: mle-team
